import re
from typing import Tuple

# Regex to detect medical diagnosis or prescription phrasing in AI advisory outputs
DIAGNOSIS_PATTERNS = [
    r"\bdiagnos(?:ed|is|ing)\b",
    r"\byou have\b",
    r"\bpatient has\b",
    r"\bcondition is confirmed as\b",
    r"\bdefinitive diagnosis\b"
]

PRESCRIPTION_PATTERNS = [
    r"\bprescribe\b",
    r"\btake \d+\s*(?:mg|ml|tablets?|capsules?)\b",
    r"\bdosage:\b",
    r"\badminister\b",
    r"\bstart medication\b"
]

DISPOSITION_PATTERNS = [
    r"\bdischarge patient immediately\b",
    r"\bno medical care required\b",
    r"\bguaranteed safe\b",
    r"\bdefinitive triage outcome\b"
]

def check_ai_safety_compliance(text: str) -> Tuple[bool, str]:
    """
    Validates that text generated by AI does not contain definitive diagnoses,
    medication prescriptions, or autonomous medical dispositions.
    Returns (is_safe, violation_reason).
    """
    if not text:
        return True, ""
    
    text_lower = text.lower()
    
    for pat in DIAGNOSIS_PATTERNS:
        if re.search(pat, text_lower):
            return False, f"Prohibited diagnostic language detected matching pattern '{pat}'"
            
    for pat in PRESCRIPTION_PATTERNS:
        if re.search(pat, text_lower):
            return False, f"Prohibited prescription/dosage language detected matching pattern '{pat}'"
            
    for pat in DISPOSITION_PATTERNS:
        if re.search(pat, text_lower):
            return False, f"Prohibited autonomous clinical disposition language detected matching pattern '{pat}'"
            
    return True, ""
